import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import api from "../api/axios";

export default function useInspectionPart3ViewModel(inspectionId) {
    const navigate = useNavigate();
    const [loading, setLoading] = useState(true);
    const [formData, setFormData] = useState({
        Findings: "",
        Post_Final_Inspection: "",
        NDTs: "",
        Recommendations: "Nil"
    });

    useEffect(() => {
        const fetchInspection = async () => {
            if (!inspectionId) return;
            try {
                const response = await api.get(`/inspection/${inspectionId}`);
                const data = response.data;
                setFormData({
                    Findings: data.Findings || "",
                    Post_Final_Inspection: data.Post_Final_Inspection || "",
                    NDTs: data.NDTs || "",
                    Recommendations: data.Recommendations || "Nil"
                });
            } catch (error) {
                console.error("Failed to fetch inspection:", error);
                alert("Failed to load inspection details.");
            } finally {
                setLoading(false);
            }
        };

        fetchInspection();
    }, [inspectionId]);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleSubmit = async () => {
        try {
            setLoading(true);
            await api.put(`/inspection/${inspectionId}`, {
                ...formData,
                Status: "Completed"
            });
            alert("Inspection report updated successfully!");
            return true;
        } catch (error) {
            console.error("Failed to update inspection:", error);
            alert("Failed to save report.");
            return false;
        } finally {
            setLoading(false);
        }
    };

    const generateAndUploadReport = async () => {
        try {
            setLoading(true);

            console.log("=== FETCHING DATA FOR REPORT ===");
            console.log("Inspection ID:", inspectionId);

            // Fetch all data
            const results = await Promise.all([
                api.get(`/inspection/${inspectionId}`),
                api.get(`/photo/inspection/${inspectionId}`)
            ]);

            const inspRes = results[0];
            const photosRes = results[1];

            if (!inspRes || !inspRes.data) {
                throw new Error("Inspection Data Invalid");
            }

            const inspectionData = inspRes.data;
            console.log("✅ Inspection data loaded");

            const photos = (photosRes && Array.isArray(photosRes.data)) ? photosRes.data : [];
            console.log("✅ Photos loaded:", photos.length);

            // Fetch equipment and inspector
            let equipment = {};
            let inspector = {};

            if (inspectionData.EquipID) {
                try {
                    const eqRes = await api.get(`/vessel/${inspectionData.EquipID}`);
                    equipment = eqRes.data || {};
                    console.log("✅ Equipment loaded");
                } catch (e) {
                    console.warn("⚠️ Failed to load equipment");
                }
            }

            if (inspectionData.UserID_Inspector) {
                try {
                    const insRes = await api.get(`/inspector/${inspectionData.UserID_Inspector}`);
                    inspector = insRes.data || {};
                    console.log("✅ Inspector loaded");
                } catch (e) {
                    console.warn("⚠️ Failed to load inspector");
                }
            }

            // Use current form data
            const finalInspectionData = {
                ...inspectionData,
                Findings: formData.Findings || "",
                Post_Final_Inspection: formData.Post_Final_Inspection || "",
                NDTs: formData.NDTs || "",
                Recommendations: formData.Recommendations || ""
            };

            console.log("=== GENERATING DOCX via Frontend ===");

            // Import and use the frontend document generator
            const { generateDoc } = await import('./docGenerator');

            const docBlob = await generateDoc(
                finalInspectionData,
                equipment,
                inspector,
                photos
            );

            console.log("✅ DOCX generated by frontend:", docBlob.size, "bytes");

            // Convert to PDF
            let pdfUrl = null;
            try {
                console.log("=== CONVERTING TO PDF ===");
                const convertFormData = new FormData();
                convertFormData.append("file", docBlob, "report.docx");

                const convertRes = await api.post("/report/convert", convertFormData, {
                    headers: { "Content-Type": "multipart/form-data" },
                    responseType: "blob",
                    timeout: 120000
                });

                const pdfBlob = convertRes.data;
                console.log("✅ PDF converted:", pdfBlob.size, "bytes");

                const pdfUploadData = new FormData();
                pdfUploadData.append("file", pdfBlob, `Inspection-${inspectionId}-${Date.now()}.pdf`);
                const pdfUpRes = await api.post("/report/upload", pdfUploadData, {
                    headers: { "Content-Type": "multipart/form-data" }
                });
                pdfUrl = pdfUpRes.data.url;
                console.log("✅ PDF uploaded:", pdfUrl);

            } catch (pdfErr) {
                console.warn("⚠️ PDF conversion failed:", pdfErr.message);
            }

            // Upload DOCX
            console.log("=== UPLOADING DOCX ===");
            const uploadFormData = new FormData();
            uploadFormData.append("file", docBlob, `Inspection-${inspectionId}-${Date.now()}.docx`);

            const uploadRes = await api.post("/report/upload", uploadFormData, {
                headers: { "Content-Type": "multipart/form-data" }
            });

            const docxUrl = uploadRes.data.url;
            console.log("✅ DOCX uploaded:", docxUrl);

            // Update database
            console.log("=== UPDATING DATABASE ===");
            let reportExists = false;
            try {
                await api.get(`/report/${inspectionId}`);
                reportExists = true;
            } catch (e) {
                reportExists = false;
            }

            const updatePayload = {
                WordFile: docxUrl,
                PdfFile: pdfUrl,
                Comment: ""
            };

            if (reportExists) {
                await api.put(`/report/${inspectionId}`, updatePayload);
                console.log("✅ Report updated in database");
            } else {
                await api.post("/report/", {
                    InspectionID: Number(inspectionId),
                    ...updatePayload
                });
                console.log("✅ Report created in database");
            }

            console.log("=== REPORT GENERATION COMPLETE ===");
            return { docx: docxUrl, pdf: pdfUrl };

        } catch (error) {
            console.error("❌ Report generation failed:", error);
            throw error;
        } finally {
            setLoading(false);
        }
    };

    return {
        formData,
        loading,
        handleChange,
        handleSubmit,
        generateAndUploadReport,
        navigate
    };
}
